Presets management
riadvice/hivelvet pull request #148
Opened 2022-05-31 10:21 UTC by hanazarraa

2022-07-19 21:50 UTC, GhaziTriki requested changes
The name of preset category, subcategory is confusing.
By just checking the UI I can see that we have:
- Preset that has a name.
- Preset has multiple "Configuration Group".
- Each configuration group has a "Configuration Entry".
Did I miss anything else?

2022-07-19 21:50 UTC, GhaziTriki commented on 20220511140915_create_preset_category_table.php
> +            ->addColumn('icon',"string",["null"=>true])
I don't think we need the icon name here. It should be guessable from the category name. Convention over configuration.

2022-07-19 21:50 UTC, GhaziTriki commented on 20220511140915_create_preset_category_table.php
> +    public function change(): void
I think we are using `up` by convention.

2022-07-19 21:50 UTC, GhaziTriki commented on hivelvet-backend/app/src/Actions/Presets/Add.php
> +        $categories = preg_filter('/^Enum\\\Presets\\\[A-Z a-z]*/', '$0', array_keys($classMap));
Looks like a Titan work :rocket: !! Well done. However can you help simple human understand it by adding comment lines?

2022-07-19 21:50 UTC, GhaziTriki commented on hivelvet-backend/app/src/Enum/Presets/Audio.php
> +    public static string $icon                                    = 'AudioOutlined';
I don't think we need the icon name here. We can find it by matching the class name.

2022-07-19 21:50 UTC, GhaziTriki commented on hivelvet-backend/app/src/Models/SubCategoryPreset.php
> +    public function PresetAndSubCategoryExists($preset_id, $subcategory_id)
Method name starts by capital letter.

2022-07-19 21:51 UTC, GhaziTriki commented on hivelvet-backend/app/src/Actions/Presets/Delete.php
> +            $this->logger->info('preset successfully deleted');
We need to print the preset id.

2022-11-29 12:52 UTC, GhaziTriki approved these changes

2022-11-29 12:53 UTC, merged

2022-11-29 17:11 UTC, SaoussenBlk commented
#87 #51  #73