Add BBB Requester & implement create and join APIs
riadvice/hivelvet pull request #357
Opened 2023-01-02 13:04 UTC by SaoussenBlk

2023-01-03 13:57 UTC, GhaziTriki requested changes

2023-01-03 13:57 UTC, GhaziTriki commented on hivelvet-backend/app/config/routes.ini
> +GET     @rooms_start    : /rooms/start/@id       = Actions\Rooms\Start->execute
Can we use POST instead of GET for room start? It will prevent most of common users from starting it by mistake using a browser.

2023-01-03 13:57 UTC, GhaziTriki commented on hivelvet-backend/app/src/Actions/Rooms/Add.php
> +                            $room->meeting_id = bin2hex(openssl_random_pseudo_bytes(8));
We should have a "unique" meeting_id per room. Recordings of the same room can be fetched using that same id.

2023-01-03 13:57 UTC, GhaziTriki commented on hivelvet-backend/app/src/Application/Bootstrap.php
> +            default   => 'GET',
What is this for?

2023-01-04 08:31 UTC, SaoussenBlk commented on hivelvet-backend/app/src/Application/Bootstrap.php
> +            default   => 'GET',
verb of allowed route

2023-01-09 18:51 UTC, GhaziTriki approved these changes

2023-01-09 18:54 UTC, merged